export {Navbarx} from './Navbarx';
export {AboutUs} from './AboutUs';
export {HeaderSection} from './HeaderSection';
export {Footer} from './Footer';
// export {Article} from './Article';
export {Features} from './Features';
export {ParallaxBG} from './ParallaxBG';
export {VideoClip} from './VideoClip';
export {People} from './People';
export {Github} from './Github';
export {Ready} from './Ready';
export {Reddit} from './Reddit';
export {LatestNews} from './LatestNews';
export {Opinions} from './Opinions';
export {Contact} from './Contact';
